language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi

script: phpunit -v --coverage-text -c ./tests/phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
