language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

script:
  - composer install
  - ./vendor/bin/phpunit -v --coverage-text -c ./tests/phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
